version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-fantasy-network
    restart: always

  app:
    image: ghcr.io/l3ktro/fantasy-api:latest
    container_name: backend-server-fantasy
    ports:
      - "30904:30904"
    depends_on:
      - db
    networks:
      - backend-fantasy-network
    restart: always


networks:
  backend-fantasy-network:
    driver: bridge
volumes:
  postgres_data:
